@BASE_URL = http://localhost:3000/api
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmE3ZDU3ZDZkNmFjZjk3NjRkMGNiNiIsInR5cGUiOiJ1c2VyIiwiaWF0IjoxNzc4MDU3OTc3LCJleHAiOjE3ODA2NDk5Nzd9.GoeCNhM0YQQNMH3a4U4sR2XidRcgqr6GneJvvruuN4c



POST {{BASE_URL}}/posts
Authorization: {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="content"

Mi primer post con una imagen
------WebKitFormBoundary
Content-Disposition: form-data; name="media"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
------WebKitFormBoundary--

###

### 2. Crear post CON DOS IMÁGENES
POST {{BASE_URL}}/posts
Authorization: {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="content"

Mi post con dos imágenes
------WebKitFormBoundary
Content-Disposition: form-data; name="media"; filename="image1.jpg"
Content-Type: image/jpeg

< ./image1.jpg
------WebKitFormBoundary
Content-Disposition: form-data; name="media"; filename="image2.jpg"
Content-Type: image/jpeg

< ./image2.jpg
------WebKitFormBoundary--

###

### 3. Crear post SIN imágenes
POST {{BASE_URL}}/posts
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "content": "Post sin imágenes"
}

###
