@BASE_URL = http://localhost:3000/api

### REGISTER A TALENT
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
  "role": "talent",
  "name": "Paco",
  "email": "paco@mail.com",
  "password": "password"
}

### LOGIN A TALENT
# @name loginTalent
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
  "email": "paco@mail.com",
  "password": "password"
}

### GET USER
GET {{BASE_URL}}/users/profile
Authorization: Bearer {{loginTalent.response.body.token}

### UPDATE USER
PUT {{BASE_URL}}/users/profile
Authorization: Bearer {{loginTalent.response.body.token}
Content-Type: application/json

{
  "password": "Paco1"
}

### REGISTER AN ADMIN
# @name registerAdmin
POST {{BASE_URL}}/users/register
Content-Type: application/json

{
  "role": "admin",
  "name": "Julio",
  "email": "julio@mail.com",
  "password": "password"
}

### LOGIN AN ADMIN
# @name loginAdmin
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
  "email": "{{registerAdmin.response.body.email}}",
  "password": "password"
}

### GET ALL USERS *ADMIN*
GET {{BASE_URL}}/users?role=admin
Authorization: Bearer {{loginAdmin.response.body.token}}

### GET ALL USERS BY LOCATION *ADMIN*
GET {{BASE_URL}}/users?role=admin&location=barcelona
Authorization: Bearer {{loginAdmin.response.body.token}}

### GET ALL USERS BY SKILL *ADMIN*
GET {{BASE_URL}}/users?role=admin&skill=malabars
Authorization: Bearer {{loginAdmin.response.body.token}}